#!/bin/bash

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
# Usage: wg-ui [ start | stop | restart | status ] [ INTERFACE ]
#        wg-ui [ install | update ]                [ INTERFACE ] [ PORT ] [FQDN]
# 	 wg-ui [ help | version ]
# 
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#   
# 2022-11-27 0.1 initial Version
# 2022-11-29 0.2 added BASE_PATH for revers proxy config
# 2022-11-29 0.3 added install function, minor bug fixes
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

SCRIPTNAME=wg-ui
SCRIPTPATH=/usr/bin
VERSION=0.3
WGIF=$2
WGCONF=/etc/wireguard/${WGIF}.conf
BASEPATH=/${WGIF}

WGUIPORT=$3
WGUIFQDN=$4
WGUIFILE=wireguard-ui
WGUIHOME=/home/${WGIF}
WGUIENVFILE=${WGUIHOME}/${WGIF}.env
WGUIPASSWORD=$( wg genkey )
WGUIUSERFILE=/home/${WGIF}/db/server/users.json
GUIEXECPATH=/usr/local/bin
GUIEXEC=${GUIEXECPATH}/wireguard-ui

SERVICE=wg-ui-${WGIF}.service
SERVICEDIR=/etc/systemd/system
SERVICEFILE=${SERVICEDIR}/${SERVICE}

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# wg-ui specitic functions

create_service() {
	# gernerate wg-ui service file
	cat << EOF | sudo tee -a > ${SERVICEFILE}
[Unit]
Description=WireGuard UI for ${WGIF}
Documentation=https://github.com/ngoduykhanh/wireguard-ui
After=network.target network-online.target
Requires=network-online.target
AssertFileIsExecutable=${GUIEXEC}

[Service]
Type=simple
EnvironmentFile=${WGUIENVFILE}
WorkingDirectory=${WGUIHOME}
ExecStart=${GUIEXEC} -bind-address 0.0.0.0:${WGUIPORT} 
Restart=on-failure
SyslogIdentifier=${SERVICE}
User=${WGIF}
Group=${WGIF}

[Install]
WantedBy=multi-user.target
EOF
}

create_wg-environment() {
	# gernerate wg-ui env file
	cat << EOF | sudo tee -a > ${WGUIENVFILE}
WGUI_USERNAME=admin
WGUI_PASSWORD=${WGUIPASSWORD}
WGUI_ENDPOINT_ADDRESS=${WGUIFQDN}
WGUI_CONFIG_FILE_PATH=${WGCONF}
BASE_PATH=/${WGIF}
WGUI_SERVER_INTERFACE_ADDRESSES=10.0.0.1/24
WGUI_SERVER_LISTEN_PORT=${WGUIPORT}
EOF

	sudo chown ${WGIF}:${WGIF} ${WGUIENVFILE}
	
	echo "==============================="
	echo "= Settings"
	echo "= * WGUI-URL=http://${WGUIFQDN}:${WGUIPORT}"
	echo "= * username=admin"
	echo "= * password=${WGUIPASSWORD}"
	echo "==============================="
}

create_wgconfig () { 

	# gernerate initial wg config file
	cat << EOF | sudo tee -a > ${WGCONF}
[Interface]
Address = 10.0.0.1/24
ListenPort = ${WGUIPORT}
PrivateKey = $( wg genkey )
EOF
	sudo chown root:${WGIF} ${WGCONF}
	sudo chmod 664 ${WGCONF}
}

update() {
	WGURL=https://github.com/ngoduykhanh/wireguard-ui/releases
	VER=$(curl -sI ${WGURL}/latest | grep "location:" | cut -d "/" -f8 | tr -d '\r')
	WGUITAR=wireguard-ui-${VER}-linux-amd64.tar.gz
	WGUIFILE=wireguard-ui

	echo "downloading wireguard-ui $VER"
	curl -sL "${WGURL}/download/${VER}/wireguard-ui-${VER}-linux-amd64.tar.gz" -o wireguard-ui-${VER}-linux-amd64.tar.gz

	echo -n "extracting "; tar xvf ${WGUITAR}
 	
	sudo chown root:root ${WGUIFILE}
	sudo mv ${WGUIFILE} ${GUIEXEC}
	rm ${WGUITAR} 

	# service renew 
	service_del
	service_add

	sudo systemctl restart ${SERVICE} 
}

install() {
	# inital wg config
	create_wgconfig 

	# create initial environment
        create_wg-environment

	# create user
	sudo useradd -m ${WGIF}

	update
}

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# framework functions

service_add() {
	create_service
	sudo systemctl daemon-reload
	sudo systemctl enable ${SERVICE} 
	echo "service ${SERVICE} added"
	echo ""
	echo "Usage: sudo systemctl start|stop|status ${SERVICE}"
}

service_del() {
	sudo systemctl disable ${SERVICE} 
        sudo rm ${SERVICEFILE}
	sudo systemctl daemon-reload 
	echo "service ${SERVICE} deleted"
}

version() {
	echo ${SCRIPTNAME}" "${VERSION}
}

help() {
	case "$1" in
	1)
		echo "Usage: wg-ui [ start | stop | restart | status ] [ INTERFACE ]"
		echo "       wg-ui [ help ]"
		;;
	2)	
		echo "Usage: wg-ui [ start | stop | restart | status ] [ INTERFACE ]"
		echo "       wg-ui [ install | update ]                [ INTERFACE ] [ PORT ] [DOMAIN/URL]"
		echo "       wg-ui [ help | version ]"
		;;
	*)	
		echo "What are you doing?"
		exit 1
		;;
	esac
}

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
# main

case "$2" in
'')
	case "$1" in
	version)
		version
		;;
	help)
		help 2
		;;
	*)
		help 1
		exit 1
		;;
	esac
	;;
*)
	case "$1" in
	start|stop|restart|status)
		sudo systemctl $1 ${SERVICE}
		;;
	install|update)
		case "$3" in
			'')
				help 2
				exit 1
				;;
			*)
				case "$4" in
				'')
					help 2
					exit 1
					;;
				*)
					$1
					;;
				esac
				;;
			esac
			;;
	help)
		help 2
		;;
	*)
		help 1
		exit 1
		;;
	esac
	;;
esac

exit 0

